# Generated by Django 4.1.7 on 2023-06-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('useremail', models.EmailField(default='', max_length=50)),
                ('usermessage', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
